- setup.py
to execute the extras_require installs: 
`cd path/to/cogent3`
`pip install -e .[dev]`
> ENH: facilitated installs for developers in setup.py, enhances #211

- src/cogent3/app/io.py
[CHANGED] assigned to local name preceded by _ to ensure distinction
from composable apps with similar names.
> MAINT: modified import of seq loading functions into app.io

- src/cogent3/util/deserialise.py
- src/cogent3/util/misc.py
- tests/test_util/test_misc.py
[NEW] robust handling of input data (anything other than a string or Path
returns False) and arbitrary string data (for example a phylogenetic
tree), returning True only if its a valid path and exists
> ENH: added cogent3.util.misc.path_exists function

- src/cogent3/app/evo.py
[FIXED] model uses load_tree if path_exists, otherwise uses make_tree
> caught bug just introduced

- tests/test_app/test_app_mpi.py
[FIXED] test only makes sense when it's being run by MPI. Now use
unittest.skipUnless decorator to check for this.
[CHANGED] moved file to test_app/test_app_mpi.py, since that's
what it's really about
> TST: fixed test_mpi failure

- src/cogent3/align/progressive.py
[CHANGED] now add the name of the substitution model and the
guide tree newick string to the info attribute of the returned alignment
object.
> ENH: additional meta-data added to alignment.info by TreeAlign

- doc/app/align-codon.rst
- doc/app/align-protein.rst
- src/cogent3/app/io.py
- tests/test_app/test_io.py
[FIXED] simplifies logic and makes function name consistent with
top level standalone funcs, i.e. load means read from file
> API: the app.io.load_(un)aligned only loads from file, fixes #180

- src/cogent3/__init__.py
[FIXED] deprecation message for LoadTree now corrected to redirect to
load_tree and make_tree
[CHANGED] LoadTable now delegates to its successor functions
> MAINT: supplementary changes related to LoadTable deprecation

- src/cogent3/evolve/solved_models.py
- tests/test_evolve/test_likelihood_function.py
[NEW] invoke test of solved substitution model in likelihood calculation,
setting rate_matrix_required=False
[CHANGED] refactored _solvedNucleotide function to _solved_nucleotide
> TST: add test of a solved substitution model

- src/cogent3/core/annotation.py
- tests/test_core/test_features.py
Copied the annotation writing from SequenceI.to_rich_dict() into _Serialisable.to_rich_dict().
Could not find a good way to remove this code duplication without adding complexity.
Added a test to demonstrate this working.
> to_rich_dict works on annotated annotations

- src/cogent3/core/alignment.py
- tests/test_core/test_alignment.py
Changing the .named_seqs attribute to .get_seq(name) had no effect on the gaps, as .get_seq directly calls .named_seqs. 
However the current implementation does remove gaps if using the Alignment class, but not the SequenceCollection class. I have made a test to demonstrate this.
> SequenceCollection.annotate_from_gff works in Alignment subclass, but not in the generic SequenceCollection class

- src/cogent3/core/alignment.py
- src/cogent3/core/sequence.py
- src/cogent3/parse/gff.py
- tests/data/gff2_test.gff
- tests/data/test_gff2.gff
- tests/test_parse/test_gff.py
Could not get cogent3.util.misc.open_(f) to work with pathlib.Path.
Allowed input as StringIO to keep old tests, and I guess backwards compatibility.
Converted the example gff2 data `data_lines` to a file to be read in so it could be checked with existing results.
> Refactored parse.gff

- src/cogent3/app/__init__.py
- src/cogent3/app/align.py
- src/cogent3/app/dist.py
- src/cogent3/app/evo.py
- src/cogent3/app/io.py
- src/cogent3/app/sample.py
- src/cogent3/app/translate.py
- src/cogent3/app/tree.py
Hi Gavin! 
I found this ticket was very related to the tasks I did before, so I implemented some codes to fix it, hope you don't mind, feel free to leave comments there, I will fix it as soon as possible! Many thanks for your teaching! 
Basically, I implemented a very simple pattern to composable apps to make available_apps be able to display input/output/data types. 
By the way, I was also thinking to put this block of codes
`
super(compassable_app_here, self).__init__(
input_types=self._input_types,
output_types=self._output_types,
data_types=self._data_types,
)
`
into its parent class, but this approach worked not very well, to avoid breaking current structure. I finally adopted the simplest modification. Hope you can have a look! 
Thanks Gavin!
> available_apps are now displaying input/output/data types, #199

- src/cogent3/draw/dendrogram.py
Dendrogram scale bar text re-aligned and remains consistently above scale line with plot is scaled.
> Dendrogram scale bar text re-aligned, fixes #444

- src/cogent3/app/composable.py
- src/cogent3/util/parallel.py
[FIXED] some systems indicate CPUs as the number of hyperthreads,
but mpi4py counts CPU cores. We now force max_workers to
be the minimum of UNIVERSE_SIZE - 1, or the user specified
value.
> BUG: setting max_workers for MPI now uses UNIVERSE_SIZE

- src/cogent3/__init__.py
[CHANGED] these were marked for removal in the 2020.1 release (coming soon)
> DEP: removed the LoadSeqs, LoadTable, LoadTree functions

- src/cogent3/core/alignment.py
- tests/test_core/test_alignment.py
[CHANGED] ref_name defaults to "longest", allows picking an arbitrary sequence
as the reference
> API: Alignment.to_html argument longest_ref changed to ref_name

- src/cogent3/core/moltype.py
- src/cogent3/core/sequence.py
- tests/test_core/test_alignment.py
- tests/test_core/test_moltype.py
[FIXED] this allows improved handling of input that is already a regex
> ENH: moltype to_regex raises exception if input seq not valid

- src/cogent3/core/alignment.py
- src/cogent3/core/location.py
- tests/test_core/test_alignment.py
[NEW] zeroed() method returns a new instance with the start at 0
[CHANGED] Sequence.deepcopy(sliced=True) now uses the zeroed method
> BUG: new Map.zeroed() method and usage, fixes #487

- src/cogent3/core/alignment.py
- src/cogent3/core/location.py
- tests/test_core/test_alignment.py
[FIXED] now uses length of self.span_covering_all()
[CHANGED] Added more sample data to test_sliced_deepcopy(), exposed
bug.
> BUG: Map.zeroed() now correctly computes parent length

- src/cogent3/core/tree.py
- src/cogent3/util/parallel.py
- tests/test_maths/test_stats/test_jackknife.py
The python syntax warning
`SyntaxWarning: "is not" with a literal. Did you mean "!="?`
arises because 'is not' and 'is' are used to check whether two objects are exactly the same (their id and values are equal). The instances where these expressions are used in cogent have been replaced by '!=' and '==' to make the correct comparison.
> Explored SyntaxWarnings associated to using py38

- tests/test_maths/test_measure.py
[CHANGED] the i386, armel CPUs have lower floating point precision. I've increased
the asbolute tolerance in the testing (for these functions only) to 4x machine
precision. This "may" fix the reported issue.
> TST: tweak the atol values for evaluating jsd/jsm cases that produce 0, #534

- src/cogent3/app/data_store.py
[FIXED] untrapped exceptions can cover multiple lines, in which case, they
are now associated with the last tracked log record.
> BUG: DataStore.summary_logs now longer fails on exceptions in the log

- src/cogent3/evolve/fast_distance.py
- tests/test_evolve/test_distance.py
[NEW] returns table with a "names" column that also acts as a row
index. Thus you can index by named pairs, e.g. table["A", "B"]
> ENH: DistanceMatrix.to_table()

- src/cogent3/app/result.py
[CHANGED] at least one of the identifiability conditions for non-stationary
continuous-time models is numerically difficult to assess, i.e. unique_Q is
incompletely checked. We defaulted to None in those cases. The unique_Q and DLC
attributes of the model_result object will return True unless the checking
algorithms successfully complete. This is a permissive setting!
> API: significant change to identifiability checks on model_result object

- doc/examples/handling_tabular_data.rst
- src/cogent3/__init__.py
- src/cogent3/core/genetic_code.py
- src/cogent3/core/moltype.py
- src/cogent3/evolve/distance.py
- src/cogent3/evolve/fast_distance.py
- src/cogent3/evolve/likelihood_function.py
- src/cogent3/evolve/likelihood_tree.py
- src/cogent3/evolve/substitution_model.py
- src/cogent3/util/dict_array.py
- src/cogent3/util/table.py
- tests/test_draw/test_draw_integration.py
- tests/test_util/test_table.py
[CHANGED] both load_table and make_table now have argument
index=<column name>. Old arg still supported, but deprecation
warning added.
> API: rename Table row_ids arg to index

- setup.py
[CHANGED] since we now use numba, and no longer compile Cython extensions against
numpy, we no longer require numpy be installed.
> MAINT: no longer require numpy prior to installation

- src/cogent3/format/table.py
- src/cogent3/util/table.py
- tests/test_util/test_table.py
[FIXED] table.array would fail if a column had tuples or lists as elements
[FIXED] table.format_cells now handles array elements
> BUG: Table operations handle cell values that are python objects

- src/cogent3/draw/dendrogram.py
- tests/test_draw/test_dendrogram.py
style_edges check if edges are present in tree.
lowered cut-off for scale_bar to be in scientific notation.
> dendrogram.py improvements, fixes #559 and #560

- src/cogent3/__init__.py
- src/cogent3/core/genetic_code.py
- src/cogent3/core/sequence.py
- src/cogent3/parse/genbank.py
- tests/test_core/test_alignment.py
- tests/test_core/test_core_standalone.py
- tests/test_parse/test_genbank.py
Two bugs affecting using GenBank files have been squashed. The first arose from using the string name of a
moltype directly on RichGenbankParser. The second, when trying to use a sequence annotation when
sequence was derived from a GenBank file, but it was loaded into a sequence collection.
Have also changed the feature attributed used to name Features.
> Bug fixes and other changes

- doc/api/__init__/cogent3.__init__.load_aligned_seqs.rst
- doc/api/__init__/cogent3.__init__.load_table.rst
- doc/api/__init__/cogent3.__init__.load_tree.rst
- doc/api/__init__/cogent3.__init__.load_unaligned_seqs.rst
- doc/api/__init__/cogent3.__init__.make_aligned_seqs.rst
- doc/api/__init__/cogent3.__init__.make_seq.rst
- doc/api/__init__/cogent3.__init__.make_table.rst
- doc/api/__init__/cogent3.__init__.make_tree.rst
- doc/api/__init__/cogent3.__init__.make_unaligned_seqs.rst
- doc/api/index.rst
[CHANGED] api\index.rst now inculdes Major utility functions
from cogent3.__init__
[ADDED] rst files under api for each function in cogent3.__init__
> DOC: added pages under API for cogent3.__init__ functions, fixes #711

- src/cogent3/util/table.py
[FIXED] Table.set_repr_policy() docstring now consistent with numpydc
[CHANGED] Added shape info prefix when using Table.head() or Table.tail()
> MAINT: improved docstring and shape info

- src/cogent3/maths/stats/distribution.py
- tests/test_maths/test_stats/test_distribution.py
[NEW] cogent3.maths.stats.distribution has probability_points
function that produces a series of evenly spaced probability
points
[NEW] cogent3.maths.stats.distribution has theoretical_quantiles
function that (using the above) returns the quantiles from a
theoretical distribution. Currently support only uniform, chisq,
t-distribution and normal.
> ENH: added functions for quantile analyses and visualisation

- src/cogent3/core/alignment.py
[CHANGED] when setting ref as longest and there are multiple
sequences matching that criteria, use alphabetical ordering
to select the reference name
> MAINT: for _repr_html_ impose alphabetical ordering on ref

- src/cogent3/util/dict_array.py
- tests/test_util/test_table.py
[FIXED] Slicing Table rows using a series of int failed if index_name
defined. This was due to DictArray not handling a list of integers,
or a numpy array. Now it does.
> BUG: robust table slicing when index_name defined

- src/cogent3/format/table.py
- tests/test_util/test_table.py
[FIXED] was failing if numpy array had python objects, like a
list or tuple, as elements
> BUG: formatted_array assumes series is a column

- src/cogent3/evolve/likelihood_function.py
- src/cogent3/format/table.py
- src/cogent3/util/dict_array.py
- src/cogent3/util/modules.py
- src/cogent3/util/table.py
- tests/test_evolve/test_likelihood_function.py
- tests/test_util/test_dictarray.py
- tests/test_util/test_table.py
Includes deprecation warning of `Table.to_rich_html()` and introduces `Table.to_html()` as its replacement.
> Refactor of Table to enable column based formatting

- src/cogent3/app/composable.py
- src/cogent3/maths/stats/contingency.py
- tests/test_app/test_composable.py
- tests/test_app/test_evo.py
- tests/test_app/test_tree.py
[CHANGED] use texwrap to break up really long string representations
into ~80 character long lines
> ENH: wrap composable app string repr

- src/cogent3/core/profile.py
- tests/test_core/test_profile.py
[NEW] added MotifFreqs.to_jsm() and MotifFreqs.to_jsd(). These return a
dict of pairwise Jensen-Shannon metric / divergence statistics.
Example usage: aln.counts_per_seq().to_freq_array().to_jsd()
> ENH: MotifCounts and MotifFreqs support computing pairwise stats

- src/cogent3/util/table.py
- tests/test_util/test_table.py
[CHANGED] column names are already cast to str, now strip white space around
the name.
> API: Table strips spaces from header

- src/cogent3/app/composable.py
- src/cogent3/app/data_store.py
- tests/test_app/test_io.py
[CHANGED] use the app.composable._get_source function consistently
[CHANGED] don't use Mock for testing in this case, too difficult to
track API
> MAINT: use one function to infer data source

- src/cogent3/util/parallel.py
[FIXED] prior to python3.8, the default approach for creating a new process
on MacOS was to use fork(). This changed with 3.8, which now defaults
to using spawn(). According to this blog post
https://chrissardegna.com/blog/multiprocessing-changes-python-3-8/
an effect of the 3.8 change is code cannot dereference data. What I find
puzzling is that this behaviour depends on whether client code invoking
multiprocess (in cogent3's case, that's any code running in parallel other
than via mpi) is invoked under a `if __name__ == "__main__"` condition.
This patch does fix the known failures, so I'm pushing this even though
it is not explicitly tested.
NOTE: I still have not yet established how to correctly test this!
> BUG: address changes in multiprocess in python3.8+

- src/cogent3/util/parallel.py
- tox.ini
[FIXED] mpi tests now correctly specified in tox.ini
[NEW] added tox environments py38mpi and py39mpi
> BUG: mpi execution with out specifying max_workers now correct

- src/cogent3/util/misc.py
- tests/test_util/test_misc.py
[CHANGED] internal operation now relies on creating a temporary working
directory, if not user specified, and uses a uuid as the file name,
adding the suffixes of the actual expected output path. This enables
open_ to provide the correct open function.
> BUG: atomic_write now correctly handles writing to compressed formats

- tox.ini
[CHANGED] invoke mpi4py futures correctly. To do this required ensuring
I correctly specify the tox venv environment python interpreter.
Other miscellaneous cleanup.
> TST: improve tox.ini

- src/cogent3/util/table.py
[CHANGED] Table checks whether data has contents using `if data`, which
will fail in future if data is a numpy array (it can also be a dict
or a list etc..)
> MAINT: address future warning from numpy

- src/cogent3/evolve/likelihood_function.py
- tests/test_evolve/test_likelihood_function.py
[CHANGED] if no alignment was set on the likelihood function instance,
it requires the user specify sequence_length. Now raises ValueError
if not specified.
> TST: better error message on simulate_alignment method

- src/cogent3/app/composable.py
- src/cogent3/app/evo.py
- tests/test_app/test_evo.py
[NEW] added unique_trees argument to app.model(). When True,
a new unrooted tree is build for each alignment. This is only
valid when the number of sequences in an alignment is 3.
> ENH: app.evo.model now supports unique trees per alignment

- doc/api/__init__/cogent3.__init__.get_model.rst
- src/cogent3/app/evo.py
- src/cogent3/app/result.py
- src/cogent3/evolve/models.py
- src/cogent3/evolve/ns_substitution_model.py
- src/cogent3/evolve/substitution_model.py
- tests/test_app/test_evo.py
[CHANGED] add key modelling args to get_model(), plus use
numpydoc style on substitution model classes
> DOC: added get_model() to API docs

- src/cogent3/app/data_store.py
- tests/test_app/test_data_store.py
[CHANGED] removed uninformative warning when configured to overwrite
a data store but create path is False
[CHANGED] close data store before its context disappears in a test
> MAINT: code tidy

- src/cogent3/util/dict_array.py
- tests/test_util/test_dictarray.py
[NEW] The standard python types means the result can be converted to json
> ENH: DictArray.to_dict() returns python types

- src/cogent3/app/sample.py
- tests/test_app/test_sample.py
[CHANGED] check there is input data, that it's of the correct type
[CHANGED] if not defined, set concat moltype attribute to be that of first
entry
[CHANGED] coerce output alignment to correct type
> TST: improve testing of sample.concat

- src/cogent3/app/align.py
- tests/test_app/test_align.py
[CHANGED] previously, no gaps were retained in the reference sequence.
They are now retained. This will be modestly slower than previously, but
avoids losing information if the choice of reference sequence is a bad one.
> ENH: app.align.align_to_ref now retains gaps in the reference

- src/cogent3/app/tree.py
- tests/test_app/test_tree.py
[FIXED] now correctly use the DistanceMatrix class for the most trivial case
fixed
> BUG: app.tree.quicktree now works for 2 sequences

- src/cogent3/core/alignment.py
- tests/test_core/test_alignment.py
[FIXED] always report a position as variable if multiple non-gap characters
are present
> BUG: refactor variable_positions() to correctly handle gaps

- src/cogent3/parse/genbank.py
- tests/test_parse/test_genbank.py
[CHANGED] if provided, this defines the moltype of the returned sequence,
otherwise the moltype is determined from the genbank file meta-data
> BUG: RichGenbankParser moltype argument now overrides file spec

- src/cogent3/__init__.py
- src/cogent3/app/composable.py
- src/cogent3/app/data_store.py
- src/cogent3/app/io.py
- tests/test_app/test_data_store.py
[CHANGED] made public get_data_source() function under cogent3.app.data_store,
which handles a non-exhaustive series of cases and is relied on by the
data store classes for extracting the provenance of data objects
[CHANGED] the make_(un)aligned_seqs functions now inspect both info and source
arguments for a source value. The source argument takes precedence.
> MAINT: refactor code for inferring data source

- src/cogent3/app/evo.py
- src/cogent3/evolve/substitution_model.py
- tests/test_app/test_evo.py
[NEW] This is such an important setting for modelling that
it should be directly exposed, rather than relying on users
to understand they should set it via sm_args.
NOTE: this setting overrides a value provided via sm_args.
> ENH: add optimise_motif_probs argument to app.evo.model

- src/cogent3/app/result.py
- tests/test_app/test_data_store.py
- tests/test_app/test_result.py
- tests/test_util/test_deserialise.py
[CHANGED] We now apply the get_data_source() function to provided source
value and raise a ValueError if the returned value is not a str or Path.
(Note that the data_store.DataMember is a subclass of string.)
NOTE: this affects all result types!
> API: app.result objects require source instance of str or pathlib.Path

- src/cogent3/__init__.py
- src/cogent3/core/tree.py
- tests/test_core/test_tree.py
[CHANGED] format setting now overrides file name suffix in load_tree and
Tree.write
[CHANGED] improved docstrings
> BUG: load_tree now handles pathlib.Path's as input, fixes #991

- src/cogent3/app/evo.py
- tests/test_app/test_evo.py
[FIXED] sequential fitting now works if lf_args includes specifying edges
for using a discrete-time markov process
> BUG: app.evo.model handles sequential fitting of models with mixed processes

- src/cogent3/core/sequence.py
- tests/test_core/test_sequence.py
[CHANGED] there was already a test_add! Renamed new test
and added tests for sequence content too.
> TST: rename recent test to avoid name clash

- src/cogent3/util/deserialise.py
- tests/test_util/test_deserialise.py
[NEW] the register_deserialiser class takes a series of strings
that serve to uniquely identify the "type" value in a dict
to be reconstituted using the decorated function.
This enables support for user defined custom json storage.
> ENH: public decorator supporting deserialising custom objects

- src/cogent3/__init__.py
- tests/test_core/test_core_standalone.py
[FIXED] pathlib.Path values cast to string so to_json() does not fail
> BUG: sequence collection source argument cast to str

- tox.ini
[FIXED] Fixed typo in the Python 3.10 MPI testing environment. This was super
irrittating and -- worse -- the "commands succeeded" message is misleading.
[CHANGED] set mpi num cpu's to 2
> TST: fix tox py310mpi setting

- src/cogent3/util/parallel.py
[CHANGED] concurrent.futures sometimes hangs. With some searching it seems it is
an artefact of set_start_method("fork") on macOS. According to this blog post
http://www.bnikolic.co.uk/blog/python/parallelism/2019/11/13/python-forkserver-preload.html
this approach can be unreliable if the parent state is complex (e.g. multi-threads).
The forkserver approach strips down the runtime so avoids this issue. Better yet,
it fixed the hanging parallel calculations.
> MAINT: changed how parallel generates child processes using multiprocess

- src/cogent3/evolve/parameter_controller.py
- tests/test_evolve/test_parameter_controller.py
[FIXED] only apply a pseudocount if optimising motif probs
and at least one state has zero frequency, default pseudocount is 0.5.
Thanks to Stephen Rogers for finding this!
> BUG: improve consistency in setting motif_probs on likelihood function

- src/cogent3/draw/dendrogram.py
- tests/test_draw/test_dendrogram.py
[NEW] added name="scale_bar" to shape annotation
[CHANGED] position the scale bar outside (above or below) the y-limits
of the dendrogram
> ENH: enhance placement of dendrogram scale bars

- .sourcery.yaml
[NEW] define the minimum supported python version. This limits
sourcery to suggesting language features consistent with the
python version specified in this file.
> DEV: added config file for sourcery.ai

- src/cogent3/util/io.py
- tests/test_util/test_io.py
[CHANGED] test_io.py now uses pytest, not unittest. Have taken advantage of
parameterize to simplify evaluating different test conditions.
[CHANGED] made open_url and open_ default to the same reading mode
[NEW] the io.open functions now handle case where mode=None
> TST: refactory io tests to using pytest

- src/cogent3/parse/fasta.py
- src/cogent3/util/io.py
- tests/test_util/test_io.py
[NEW] this enables files to be downloaded from the web using the
convenience functions,
e.g. load_aligned_seqs("https://path/to/somefile.fasta")
will now work.
[NEW] open_url() now supports "file://path/to/local/file". Mainly for
testing purposes.
[CHANGED] tests of open_url() now only use 1 remote file to reduce
test time.
> ENH: open_ now handles urls too

- src/cogent3/app/align.py
- src/cogent3/app/composable.py
- src/cogent3/app/dist.py
- src/cogent3/app/evo.py
- src/cogent3/app/io.py
- src/cogent3/app/sample.py
- src/cogent3/app/translate.py
- src/cogent3/app/tree.py
- src/cogent3/app/typing.py
- tests/test_app/test_composable.py
- tests/test_app/test_typing.py
[NEW] the cogent3/app/typing.py module contain type hints for
app interchange. These will wind up being applied to Composable._in
and Composable.._out attributes.
> ENH: initiate conversion composable apps to musing type hints

- src/cogent3/app/align.py
- src/cogent3/app/composable.py
- src/cogent3/app/dist.py
- src/cogent3/app/evo.py
- src/cogent3/app/io.py
- src/cogent3/app/sample.py
- src/cogent3/app/translate.py
- src/cogent3/app/tree.py
- tests/test_app/test_io.py
- tests/test_app/test_tree.py
[CHANGED] no longer assign to a self.main attribute. This is required
for us to define Composable.main as an abstract base class and method
Notes
There are two types of apps: apps for which there is only one possible
algorithm (e.g. cogent3.app.quick_tree); and, apps in which the algorithm
is selected based on args to the class constructor
(e.g. cogent3.app.sample.take_codon_positions). In the latter, I've chosen to
just create a separate self._func attribute which is called by <app>.main().
> DEP: refactor all apps to have a main() method, relates to #1071

- src/cogent3/app/io.py
- src/cogent3/app/result.py
- src/cogent3/core/alignment.py
- tests/test_app/test_composable.py
- tests/test_app/test_dist.py
- tests/test_app/test_evo.py
- tests/test_app/test_tree.py
@GavinHuttley 
I removed all cases of `_type` in tests. But this commit is **not** ready to merge.
Please look at this function. It cannot find `loader` when we don't have `_type` attribute. Please help me how to solve this.
```
def _set_checkpoint_loader(self):
loader = {"sequences": load_unaligned}.get(self._out._type, load_aligned)
loader = loader(format=self._format)
self._load_checkpoint = loader
```
> DEV remove test for _type attribute

- src/cogent3/app/composable.py
- tests/test_app/test_composable.py
[NEW] module level dictionary that records apps during decoration
by their object provenance. This means a 3rd party developer
could develop an app with the same class name, it would be
distinguished by it's full provenance.
> ENH: add app registry to composable decorator

- tests/test_app/test_evo.py
[CHANGED] The interception of constructor arguments using __new__ means we no
longer have a per class customised representation. This required some tweaking of
test to accomodate changed behaviour of the evo.hypothesis app.
> TST: updated test to reflect fundamental change to str representation of apps

- src/cogent3/__init__.py
[CHANGED] at some point, numba debugging messages became switched on by
default. In our case, this leads to massive log files for composable
apps. Turning this off in cogent3.__init__ until a better solution
arises.
> ENH: suppress numba debug logging

- src/cogent3/app/composable.py
- tests/test_app/test_composable.py
[NEW] converts function to a class with the same name as the
function, then does standard decoration process. Intended to
replace the user_function class / appify decorator pair.
> ENH: extend define_app supports decorating functions

- src/cogent3/align/progressive.py
- src/cogent3/app/typing.py
- tests/test_app/test_typing.py
[NEW] allows foo(name: "some_type")
[CHANGED] add constraints for SeqType
> ENH: support string literal type hints

- noxfile.py
- pyproject.toml
[CHANGED] get it to use the pyproject.toml file instead
[CHANGED] updated pyproject.toml optional-dependencies for test
to include all dependencies necessary for testing
> TST: don't specify dependencies in noxfile

- src/cogent3/core/alphabet.py
- tests/test_core/test_alphabet.py
[CHANGED] previous implementation produced a strange state order that meant
a k-mer inferred from extrapolation of bases indices into a 1D
index did not match those produced by this method. Code is simplified,
uses the itertools.product and addresses the issue.
> MAINT: fixed consistency of state order in Alphabet.get_word_alphabet

- src/cogent3/evolve/ns_substitution_model.py
- src/cogent3/evolve/substitution_model.py
- src/cogent3/util/deserialise.py
- tests/test_util/test_deserialise.py
[FIXED] key-word arguments were being serialised both at
the constructor level and within the generic ``kw`` argument
setting. These are now purged within the `MODEL.to_rich_dict()`
method. But that just exposed a difgerent issue -- the stationary
and non-stationary substitution model classes are inconsistent
in their inheritance hierarchy, and constructor signatures for
alphabets and predicates. This will need revisiting.
[CHANGED] non-stationary nucleotide based models now inherit from
NonReversibleNucleotide
[CHANGED] deserialise_model uses alphabet as kw, not arg
[NEW] add more tests for the non-stationary models
Thanks @StephenRogers1 for identifying this issue!
> BUG: non stationary independent tuple models can now be serialised

- src/cogent3/recalculation/scope.py
- tests/test_evolve/test_likelihood_function.py
[FIXED] correct argument order in using scipy.stats.distributions.chi2,
quantile first, then df
[NEW] add explicit test
> TST: test the likelihood function get_param_interval method

- src/cogent3/app/composable.py
[CHANGED] consider all iterable types and don't assume they can be indexed
[CHANGED] test_apply_to_only_appends reinstated
> MAINT: reinstate code incorrectly deleted during rebase

- src/cogent3/app/__init__.py
- tests/test_app/test_init.py
[NEW] identify provenance of callable default values
[CHANGED] split across multiple lines (as per black) for
readability
> ENH: improve readability of app_help display

- src/cogent3/app/composable.py
- tests/test_app/test_sqlite_data_store.py
[CHANGED] refactor the composable._make_logfile_name function so it
generates unique log ID's even if called on the same thread. Instead
of using the process ID, it puts the first 8 characters of a uuid4
string onto the end of the name.
[NEW] test that append operation creates a new logfile for directory
and sqlite data stores
> MAINT: changes to allow testing of append to data store

- src/cogent3/app/composable.py
[CHANGED] revert effect of previous refactor which was causing
truncation to single characters
> MAINT: correct log file name generating function

- src/cogent3/app/data_store_new.py
- tests/test_app/test_io_new.py
[NEW] If using sqlitedb and pickling records, then the data member
read returns the raw data for both completed and not completed types.
> ENH: DataStoreABC.summary_not_completed skips bytes records

- src/cogent3/app/sqlite_data_store.py
[CHANGED] If a data store is locked to the current process
then state this, the process ID is not needed.
> ENH: improved sqlitedb describe table title

- src/cogent3/app/__init__.py
- tests/test_app/test_init.py
[FIXED] renamed local variable to _app_name to minimise the chance of
TypeError
> BUG: app.get_app() works for apps with a name keyword arg

- src/cogent3/core/sequence.py
- tests/test_core/test_sequence.py
TST:
- added `test_subsequent_slice_neg_step` to ensure all conditions with negative steps are being tested
- added `test_seqview_step_0` to test that a slice with a step of 1 throws a `ValueError`
- added `test_seqview_repr` to test the representation of a SeqView object 
BUG: 
- removed untested condition that was both unnecessary and incorrect!
> TST: added tests of SeqView to address coverage gaps

- .github/ISSUE_TEMPLATE/deprecation.md
- .github/ISSUE_TEMPLATE/discontinue.md
- changelog.d/README.md
[CHANGED] double underscores gets interpreted as bold in Markdown, so
wrapping __version__ etc strings in literal (backtick) markers
> DEV: tidy formatting of scriv instructions

- src/cogent3/parse/genbank.py
- tests/test_parse/test_genbank.py
DEP: deprecating arguments on `cogent3.parse.genbank.Location` to be PEP8 compliant, fixes #1193.
DEP: deprecating coordinate handling methods on `cogent3.parse.genbank.Location`, `first` and `last` are replaced with `start` and `stop`, the former is 1-based and the latter is 0-based, fixes #1301.
> DEP: `cogent3.parse.genbank.Location` refactor

- src/cogent3/core/sequence.py
- src/cogent3/parse/sequence.py
no longer redefining built-in 'slice'.
> MAINT: refactoring argument 'slice' to 'segment' in Seqview methods

- changelog.d/20230410_151103_Gavin.Huttley.md
- src/cogent3/core/tree.py
- tests/test_core/test_tree.py
`TreeNode` is the parent of `PhyloNode`. The latter is distinct in having a `length` attribute,
corresponding to a branch length. Duplicate methods accumulated on these classes during
the PyCogent era that blurred the boundaries between them. This patch addresses that blurring,
clarifying that any method which does not involve distances belongs on the `TreeNode` class,
distance related methods only on the `PhyloNode` class.
> API: separation of concerns changes to tree classes

- src/cogent3/core/alignment.py
- tests/test_core/test_alignment.py
[CHANGED] removed over-ride of property in Alignment
[CHANGED] allow None to be assigned to SeqColl.annotation_db
> ENH: SequenceCollectiuon.annotation_db can be reset

- src/cogent3/core/location.py
- tests/test_core/test_location.py
[CHANGED] recently added and, turns out, not required
> MAINT: remove new method

- .github/workflows/testing_develop.yml
- noxfile.py
- pyproject.toml
- requirements.txt
[CHANGED] numba 0.57 is 3.11 compatible, and on my machine
all tests pass when using it. So added as explicit version for
python 3.11 in toml and requirements.
[CHANGED] Added 3.11 to supported versions in toml and noxfile
[CHANGED] Added 3.11 to GitHub action test matrix
> DEV: add support for python 3.11

- src/cogent3/align/pycompare.py
- src/cogent3/draw/dotplot.py
- tests/test_align/test_compare.py
[CHANGED] a precursor to enabling modifying the signature
> API: align.pycompare.find_matched_paths() requires keyword arguments

- changelog.d/20230525_111647_Gavin.Huttley.md
- src/cogent3/app/evo.py
- tests/test_app/test_evo.py
[NEW] We now use a function for ensuring consistency of setting bounds,
plus apply the new lower bound to all model branch length and substitution
model rate parameters.
[CHANGED] the issue was not entirely correct. It related to the fact that
param_rules that specified a rate term in a model that also defined time_het
were ignored.
> ENH: added lower bound parameter to app.model(), fixes #1452

- src/cogent3/core/annotation_db.py
- tests/test_core/test_annotation_db.py
[NEW] each argument can now take a string or bool value. The former is used
as a condition for identifying the subset of rows to apply the boolean
conditions.
> API: extended behaviour of AnnotationDb.count_distinct()

- src/cogent3/core/annotation_db.py
- tests/test_core/test_annotation_db.py
[NEW] The SqliteAnnotationDbMixin._setup_db() method can now
handle using a connection instance. If the incoming schema
is a subset of the classes schema, it is considered compatible.
Any other relationship triggers a TypeError. Check is implemented
in _compatible_schema()
> ENH: support db = a sqlite Connection instance

- src/cogent3/core/annotation_db.py
- src/cogent3/parse/fasta.py
- tests/test_parse/test_fasta.py
[NEW] implemented 2 different parsers, one for when strict is True, which
is the same as previously. The other for when strict is False. The latter
checks only for blank lines.
[CHANGED] the strict=False setting is different to previously, so behaviour
for malformed fasta files has changed.
> ENH: improve performance of fasta parser

- src/cogent3/app/align.py
- tests/test_app/test_align.py
[CHANGED] The alignment quality sp_score relies on computing pairwise
genetic distanxces. This can fail due to NaN's in those distances.
Return a more informative NotCompleted object.
> MAINT: better NotCompleted result from sp_score

- changelog.d/20230712_102325_Gavin.Huttley.md
- src/cogent3/core/alignment.py
- src/cogent3/core/sequence.py
- tests/test_core/test_alignment.py
- tests/test_core/test_core_standalone.py
- tests/test_core/test_sequence.py
[NEW] if seq / align length not divisible by 3, raises an exception
[CHANGED] deprecated allow_partial argument
[NEW] <collection>.has_terminal_stops() is being deprecated for
<collection>.has_terminal_stop(), because it returns True if a single
sequence has a terminal stop.
> API: added strict argument to has_terminal_stop() method

- tests/test_util/test_misc.py
- tests/test_util/test_warning.py
[CHANGED] the pytest.mark.filterwarning decorator does
not mask DeprecationWarning's as that is a special case
"By default pytest will display DeprecationWarning and
PendingDeprecationWarning warnings from user code and
third-party libraries, as recommended by PEP 565."
So we use the pytest.deprecated_call() context manager
within those tests.
[NEW] add UserWarning filter on another test
> TST: filter expected warnings

- src/cogent3/align/progressive.py
- src/cogent3/app/align.py
- src/cogent3/core/alignment.py
- src/cogent3/core/alphabet.py
- src/cogent3/core/moltype.py
- src/cogent3/core/sequence.py
- src/cogent3/evolve/likelihood_tree.py
- src/cogent3/evolve/motif_prob_model.py
- src/cogent3/evolve/substitution_model.py
- tests/test_core/test_moltype.py
[CHANGED] resolve_ambiguity() is now on the MolType, while get_matched_array()
is a standalone function in the likelihood_tree module (the only place
it's used).
[CHANGED] where possible, now using moltype directly rather than from alphabet
class
> DEP: moved Alphabet methods resolve_ambiguity() and get_matched_array()

- src/cogent3/app/__init__.py
- tests/test_app/test_init.py
To resolve https://github.com/cogent3/cogent3/issues/1633
> Filter available_apps by name

- src/cogent3/core/alignment.py
[CHANGED] it's not being used anywhere and we will be radically refactoring
how alignments work anyway.
> DEP: dropping the CodonArrayAlignment class

- src/cogent3/app/sample.py
- tests/test_app/test_sample.py
Related to #1636.
Not too sure about lines 67-68 here, as the order of dict items change across `pytest --doctest-module` runs`concatenated.to_dict()`
> Docstring examples for app.sample.concat and omit_degenerates.

- .github/dependabot.yml
Dependabot now checks for updates to GitHub Actions
> DEV: configure dependabot to also update github-actions

- .github/workflows/testing_develop.yml
Fixes a longstanding issue with coveralls requiring different job names for parallel builds. Otherwise, it may only accept the last job.
Under a build, coverage is displayed per job (os/python-version) and an aggregate report is displayed at the bottom.
The pull request also modifies the "finish" GitHub action job in the CI - only one parallel-finished call to coveralls is required rather than per os/python-version.
I have also modified the settings on coveralls for cogent3 to only send a status update for the overall build rather than per job. This limits the GitHub checks to only display the coverage change for the complete build instead of for each os/python-version.
> DEV: Fix coveralls job reporting

- src/cogent3/core/sequence.py
- tests/test_core/test_sequence.py
Addresses #1715.
- Add `seq_len` attribute and property
- Add tests for initialisation and `.copy()`
- Replaces `SeqView` use of `len(self.seq)` with `seq.seq_len`
> DEV: Add `seq_len` attribute to `SeqView`

- pyproject.toml
In release 2024.2.5a1, support was added for Python 3.12. This pull request updates the classifier list to include Python 3.12 as a supported language. 
Note that the supported python versions badge in the README only lists 3.9, 3.10, 3.11, not 3.12 (I believe the badge fetches data from PyPI). The incorrect badge is also shown on [cogent3's PyPI page](https://pypi.org/project/cogent3/).
> DOC: add Python 3.12 classifier

- .gitignore
- .hgignore
[NEW] exclude .devcontainer and any contents from being included
> DEV: added ignore patterns for Docker

- .github/workflows/linters.yml
Fixes a typo in the owner of `github.repository`, and the usage of the `isort` command
> DEV: fix linting action repo owner and isort command

- src/cogent3/core/annotation_db.py
Stores arrays in the sqlite database in the [.npy format](https://numpy.org/devdocs/reference/generated/numpy.lib.format.html) to restore OS independence.
Importantly, this change is not backwards compatible with previously saved databases that include numpy arrays. Notably, previous versions of `GffAnnotationDb` and `GenbankAnnotationDb` will not be able to be loaded.
Fixes #1776
> BUG: fix representation of numpy arrays in sqlite databases

- src/cogent3/core/annotation_db.py
- tests/test_core/test_annotation_db.py
Stacked on #1787.
Adds tests for the update_file_format function.
Also fixes an issue where update_file_format proceeded without error, creating a new file, when the file to be updated did not exist.
> TST: add tests for update_file_format

- src/cogent3/maths/stats/special.py
This time, I used GitHub Desktop. Previously, I used the Git command line, but there was a line ending issue: I am on a Windows system, and after downloading cogent3 to my computer, all the files had \r\n line endings instead of \n, which resulted in over a million modifications when compared to the original repository. This problem doesn't occur with GitHub Desktop. However, I still want to know how to solve this issue if using the Git command line.
> DEP: remove the erf() and erfc function fixes #1778

- src/cogent3/app/composable.py
[CHANGED] use getattr(member, "md5", None) instead.
> MAINT: app writers as_completed() no longer requires .md5 attribute

- changelog.d/20240329_152534_Gavin.Huttley.md
- src/cogent3/core/alignment.py
- tests/test_core/test_alignment.py
[FIXED] previous default was discontinued!
[NEW] test default settings of quick_tree()
> BUG: Alignment.quick_tree() defaults to pdist calculator

- src/cogent3/util/parallel.py
[CHANGED] was raising an exception if max_workers exceeds the number
of CPUs. Now just revert to the default behaviour of the maximum
number available.
> MAINT: reduce max_workers if too large

- .github/workflows/testing_develop.yml
For the CI, the setup python action does not support Python 3.9 on macos 14 (GitHub has recently been [rolling it out](https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/)).
See: https://github.com/cogent3/cogent3/pull/1822#issuecomment-2074204974
As a temporary solution, so development can proceed, I've downgraded the CI runner from macos-latest to macos-13.
> DEV: downgrade macos from latest to 13

- src/cogent3/align/pairwise.py
- src/cogent3/core/location.py
- src/cogent3/draw/dotplot.py
- tests/test_app/test_align.py
- tests/test_core/test_location.py
- tests/test_draw/test_dotplot.py
[CHANGED] reimplement the get_align_coords() function, now simpler
and more robust
[NEW] added IndelMap.get_gap_align_coordinates() returns a 2D array
of gap start, end in alignment coordinates. Used by get_align_coords().
> MAINT: use IndelMap for dotplotting

- .github/workflows/testing_develop.yml
Issue for setup-python on macos-14 has been resolved (https://github.com/actions/setup-python/issues/850#issuecomment-2077454891)!
The macos tests are now the fastest in the CI to run!
> DEV: upgrade macos back to latest

- src/cogent3/core/alignment.py
- src/cogent3/format/fasta.py
- tests/test_core/test_alignment.py
> ENH: seqcoll.to_fasta supports block_size

- doc/doctest_rsts.py
[CHANGED] default to running in serial
The issue appears to be deletion of temporary directories before usage has continued. These directories are created to isolate individual tests by the parallel processes.
> DEV: doctest_rsts tests are broken when run in parallel

- src/cogent3/app/sample.py
Added docstring examples for `cogent3.app.sample` apps:
- `take_named_seqs`
- `omit_bad_seqs`
- `take_n_seqs`
- `fixed_length` 
#1636
> app.sample docstring examples

- src/cogent3/core/alignment.py
- src/cogent3/draw/dotplot.py
[NEW] added type hints to the SequenceCollection.dotplot() method
[CHANGED] improved the docstring text describing how k is chosen.
> MAINT: type hints and docstring mods for dotplot code

- src/cogent3/core/alignment.py
[CHANGED] put the single implementation on the AlignmentI class
> MAINT: tidy __repr__ methods in Alignment classes

- tests/test_app/test_plugins.py
This test verifies that a @define_app decorated function generates apphelp from the functions docstring
> add test to check for #1844

- src/cogent3/app/align.py
- src/cogent3/app/dist.py
- src/cogent3/app/translate.py
Added docstring examples for the apps used in the wrangling paper.
`app.translate`:
- `select_translatable`
- `translate_seqs`
`app.align`:
- `progressive_align`
- `ic_score`
- `cogent3_score`
- `sp_score`
`app.dist`:
- `jaccard_dist`
- `approx_pdist`
- `approx_jc69`
#1636
> DOC: Docstring examples for `app.translate`, `app.align`, and `app.dist`

- src/cogent3/core/moltype.py
- src/cogent3/core/sequence.py
- tests/test_core/test_new_sequence.py
- tests/test_core/test_sequence.py
Updated tests use e.g. `new_moltype.DNA.make_seq()` replacing `Sequence(...)`.
> TST: Port `SeqView` tests and ruff fixes

- src/cogent3/core/new_genetic_code.py
- tests/test_core/test_new_genetic_code.py
[CHANGED] GeneticCode is now hashable, just add that to the lookup
dictionary. Now test all different input types, int, str, instance
> ENH: new get_code() handles GeneticCode instance as a value

- src/cogent3/core/new_alphabet.py
Over a particular example using timeit, with numba takes 1.8 microseconds per loop; half numba 23.3 microseconds per loop; no numba 49.5 microseconds per loop. Results follow a similar pattern for much larger sequence lengths.
> MAINT: remove profiling comment, seq_to_kmer_indices is faster with numba

- src/cogent3/app/data_store.py
- tests/test_app/test_data_store.py
[FIXED] would fail with invalid newline character if a
compression was indicated via the file suffix.
> ENH: DataStoreDirectory.write now handles compression

- src/cogent3/core/alignment.py
- src/cogent3/core/new_alignment.py
- src/cogent3/core/new_sequence.py
- tests/test_core/test_alignment.py
- tests/test_core/test_new_alignment.py
- tests/test_core/test_new_sequence.py
in this PR: 
- add `SeqViewABC`
- `SeqView` inherits from `SeqViewABC` and now requires `alphabet` as init arg
- REMOVED `replace` method from `SeqView` -- wont add back unless things break 
- methods for `translation` (pending refactoring of `Sequence.translate`)
- methods for `reverse_complement`
- increased test coverage 
- refactor targets
> DEV: `SeqViewABC` and methods for translation on `SequenceCollection`, #1901

- src/cogent3/__init__.py
- src/cogent3/core/genetic_code.py
- src/cogent3/core/moltype.py
- src/cogent3/core/new_moltype.py
- src/cogent3/core/new_sequence.py
- tests/test_core/test_new_moltype.py
- tests/test_core/test_new_sequence.py
DEV: `__bytes/array__` now complement reversed seqs - this took some changes to `Moltype.complement`, @GavinHuttley if you would prefer that the responsibility of converting the result of complement into input type is handled in the `__bytes/array__` methods let me know and I can change it 🫡
> ENH: add new_type arguments for top-level function, fixes #1924

- src/cogent3/app/composable.py
- tests/test_app/test_composable.py
Not a fix to #1897, though raises an error when it detects a top-level stringified type hint for either the input or output of an app.
By top-level, I mean it doesn't check nested type hints - i.e. patterns like `typing.Union["int","str"]`. To do so would break the current behaviour of `cogent3.app.typing.get_constraint_names`. It would be better to properly resolve the issue instead.
It will detect the problem-causing `from __future__ import annotations` pattern and raise a `NotImplementedError` for now.
> DEV: raise not implemented error on top level stringified type hint

- src/cogent3/app/evo.py
- tests/test_app/test_evo.py
> ENH: overwrite the bounds in `lf` to be consistent with the arguments specified in the `model`

- src/cogent3/core/new_moltype.py
- src/cogent3/core/new_sequence.py
- src/cogent3/core/sequence.py
- tests/test_core/test_moltype.py
- tests/test_core/test_new_moltype.py
- tests/test_core/test_new_sequence.py
- tests/test_core/test_sequence.py
- add `strip_degenerate`, `strip_bad`, `strip_bad_and_gaps`, `disambiguate` to `Moltype` -- addresses #1932
- add `count_variants`, `count_gaps`, `count_degenerate` to `Moltype` -- addresses #1938
- remove replace from sequences -- fixes #1921 
- port Sequence tests
> ENH: add strip methods to moltype

- src/cogent3/core/new_sequence.py
- tests/test_core/test_new_sequence.py
- tests/test_core/test_sequence.py
- 3 new xfails
- 3 xpasses removed
- @KatherineCaley could you check if any old ArraySeq-related tests in the following classes should be ported? If not, I think it's the last of the Sequence tests!
- DnaSequenceTests
- CodonSequenceTests
- DnaSequenceGapTests
- SequenceIntegrationTests
- ModelSequenceSequenceTests
> TST: Port Sequence unittest classes

- src/cogent3/core/alignment.py
- src/cogent3/core/new_alignment.py
- src/cogent3/core/new_moltype.py
- src/cogent3/core/new_sequence.py
- src/cogent3/core/sequence.py
- src/cogent3/evolve/motif_prob_model.py
- src/cogent3/maths/optimisers.py
- tests/test_core/test_maps.py
- tests/test_core/test_new_alignment.py
- tests/test_core/test_new_moltype.py
- tests/test_core/test_profile.py
- tests/test_core/test_sequence.py
- tests/test_evolve/test_likelihood_function.py
- tests/test_parse/test_cigar.py
in this PR: 
NEW: 
- added new `MolType.degenerate_from_seq()`, fixes #1948
DOC: 
- docstrings for view and slice record classes
- docstrings for make_seq 
DEP:
- removed deprecation warnings and deprecated arguments marked for this release
@GavinHuttley I note that the `Map` class is marked for removal at this release, however, I did not remove it
> DEV: new moltype method and some documentation

- .github/workflows/release.yml
Partial resolution of #1971. Adds a workflow which on manual trigger publishes to PyPI.
Remaining tasks:
- create a release environment
- add github actions as a trusted publisher for `cogent3` through pypi
> DEV: add release workflow

- changelog.md
- pyproject.toml
- src/cogent3/_version.py
- src/cogent3/util/io.py
- tests/test_core/test_tree.py
Closes #1984 
`charset-normalizer` incorrectly detects the encoding of some small newick files such as for the string `(a,b);`. 
This adds a test for such a case and reverts the dependency on `charset-normalizer` back to `chardet`.
> MAINT: revert `charset-normalizer` dependency to `chardet`

- src/cogent3/app/__init__.py
[CHANGED] signature no longer displays the type hint, so at least copy
and paste of the example is runnable
> ENH: changes to app_help(), fixes #1994

- src/cogent3/app/__init__.py
- tests/test_app/test_init.py
- tests/test_app/test_plugins.py
[FIXED] now covers cases that use the pipe character. Also removed
spaces around "=" character and replaced double with single quotes
in app vignette for consistency with repr(obj) style
> ENH: improve type-hint stripping in app_help()

- src/cogent3/core/location.py
- src/cogent3/core/new_alignment.py
- src/cogent3/core/new_sequence.py
- tests/test_core/test_new_alignment.py
In this PR: 
- implementing changes to the design of aligned/alignment as discussed on 30/07
- stop tracking slice history directly in `AlignedDataView`, now via a slice record object 
- generally trying to mirror the `SeqsData` design more closely in `AlignedSeqsData` - especially with the assignment of `make_seq` and `make_aligned` methods
- Slicing an `Alignment` propagates to `Aligned` instances!
> ENH: support slicing of Alignment/Aligned

- src/cogent3/core/location.py
- src/cogent3/draw/dotplot.py
- src/cogent3/util/misc.py
- tests/test_core/test_location.py
- tests/test_draw/test_dotplot.py
[NEW] IndelMap.shared_gaps() takes either another IndelMap instance,
or a numpy array which consists of start, end coordinates that
define gap locations in alignment coordinates. It returns a
numpy array with start, end coordinates for shared gaps. This
method relies on two new functions, coords_intersect() and
span_and_span() the latter defining the intersection for two
spans.
The result of this method can be applied to multiple IndelMap
instances from an alignment so that all common gaps can be
identified and then removed for each case.
[NEW] IndelMap.minus_gaps() takes either another IndelMap instance,
or a numpy array which consists of start, end coordinates that
define gap locations in alignment coordinates. It returns a
new IndelMap instance after removing shared gaps. It uses
a new …
> ENH: IndelMap gets methods for identifying and removing common gaps

- src/cogent3/core/new_moltype.py
- tests/test_core/test_new_moltype.py
[CHANGED] We had a tuple, list and frozen set between
DNA, RNA and PROTEIN IUPAC characters! Now all are tuples,
so their order is unchanged between runs and immutable.
> MAINT: new_moltype IUPAC symbol type consistency

- src/cogent3/core/new_alignment.py
- tests/test_core/test_new_alignment.py
[NEW] allow specifying the method name to be invoked in the parent
[NEW] _IndexableSeqs supports len() and repr()
[NEW]_IndexableSeqs suports indexing by int or string
[CHANGED] SequenceCollection no longer assigns to SeqsData.make_seq
[CHANGED] SequenceCollection gets a _post_init method invoked at the end
of the constructor. Overridden in Alignment so behaviour is customised.
The method assigns the _IndexableSeqs instance to a new ._seqs attribute.
The .seqs property is now returns ._seqs
> API: _IndexableSeqs class API changes

- src/cogent3/core/new_alignment.py
- tests/test_core/test_new_alignment.py
API changes
- remove `make_seq` from SeqsData
- `SeqsData.__getitem__` now returns a `SeqDataView`
> API: remove `make_seq` from SeqsData

- src/cogent3/core/new_alignment.py
- tests/test_core/test_new_alignment.py
API: remove strand as arg to seq collection constructor 
- the way I had added tracking of the strand was not practical, considering that for a sequence, its strand is the sign of its step.
DEV: change how offset is tracked
- ensure that when a sequence is created from an alignment with an offset, this is propagated to the sequence instance - this is only necessary when the abs(step) == 1, otherwise we don't need it for annotation handling 
@GavinHuttley keen for your feedback about the direction of this PR because strand/offset are both important for feature querying
> API: remove strand arg, modify offset handling for Alignments

- .github/workflows/testing_develop.yml
[CHANGED] addressing incompatibility betwen numba and python 3.13.4
by pinning to the previous minor release.
> DEV: use uv for github action and pin python 3.13.3
