cogent3/cogent3

- src/cogent3/app/align.py
- src/cogent3/app/composable.py
- src/cogent3/app/dist.py
- src/cogent3/app/evo.py
- src/cogent3/app/io.py
- src/cogent3/app/sample.py
- src/cogent3/app/translate.py
- src/cogent3/app/tree.py
Hi Gavin! Many thanks for your teaching and patience! 
I just accidentally deleted this branch, but successfully recovered it and just did this pull request. 
So, just a quick heads up: there's a procedure to recover some accidentally deleted stuff in Git. 
First: use `git reflog` to find out the id of the latest commit of the deleted branch; 
Second: use `git checkout [the_commit_id]` to switch to the commit;
Third: make sure to check out to a new branch after second step; 
Finally, just push this newly created branch.
> ENH: added constant app types, fixes #264

- src/cogent3/app/align.py
[CHANGED] removed local functions, those break pickling
and thus parallel execution
> MAINT: refactor app.align.align_to_ref

- tests/test_draw/test_dendrogram.py
these tests just exercise creation of the figure as a UnionDict
> TST: added tests of dendrogram construction

- src/cogent3/__init__.py
- tests/test_core/test_core_standalone.py
use `cogent3.make_seq` instead
> DEP: removed redundant function cogent3.Sequence

- azure-pipelines.yml
> #284 added tox py36 onto azure pipeline

- src/cogent3/app/evo.py
- src/cogent3/app/result.py
- tests/test_app/test_evo.py
[NEW] added optional parallel argument to evo.bootstrap, defaults to False
[NEW] added basic tests for the app
> BUG: fixed error in construction of bootstrap null distribution

- azure-pipelines.yml
[NEW] build source distribution for upload to pypi
[CHANGED] just test on 3.7 on Windows, it's soo slow otherwise
> DEV: updated azure pipeline

- src/cogent3/core/annotation.py
- src/cogent3/core/sequence.py
- tests/test_core/test_features.py
> `with_masked_annotations()` handles nested annotations

- tox.ini
Allows the getuser() method from getpass to function on Windows.
> TST: tox now inherits system environment variables

- doc/app/index.rst
- doc/app/user_function.rst
Thanks Gavin! Let me know anywhere needs improvement.
> ENH: added user_function docs and linked it with index, fixed #381

- src/cogent3/core/alignment.py
[CHANGED] removed SequenceCollection.__init__. Just uses the _SequenceCollection one.
[CHANGED] removed SequenceCollection.get_similar, should be on the _SequenceCollection
only.
[CHANGED] tidied docstrings
> MAINT: code tidy of patch related to #410

- src/cogent3/align/progressive.py
- tests/test_align/test_align.py
aded to ["align_params"]["lnL"]
> ENH: TreeAlign adds alignment log-likelihood to align.info

- src/cogent3/__init__.py
- src/cogent3/core/sequence.py
- tests/test_core/test_alignment.py
- tests/test_core/test_features.py
- tests/test_core/test_sequence.py
It's not clear how CI passed, but there was a clear error in the test_annotate_matches_to location.
> BUG: fixed a recently introduced testing bug

- src/cogent3/core/genetic_code.py
- tests/test_core/test_genetic_code.py
[NEW] converts an amino acid sequence to a regular expression
consisting of all possible codons for each amino acid
> ENH: genetic code gets a to_regex method

- src/cogent3/app/result.py
- tests/test_app/test_result.py
[NEW] inherits from the generic_result class, adds methods for model selection
based on AIC etc..
[CHANGED] hypothesis_result now inherits from this class
> ENH: app.result.model_collection_result, fixes #540

- src/cogent3/app/result.py
- tests/test_app/test_result.py
[NEW] specified via constructor of both classes
> ENH: model_collection_result and hypothesis_result get name attribute

- src/cogent3/draw/drawable.py
[NEW] the one distributed with plotly does not work for us due to
non-robust path introspection. We address this, will submit this
upstream at some point.
> MAINT: custom sphinx gallery renderer

- src/cogent3/maths/stats/number.py
- src/cogent3/util/table.py
- tests/test_maths/test_stats/test_number.py
- tests/test_util/test_table.py
returns a CategoryCounter. That object now has a to_table method for nicer display.
> New Table method for counting categories

- src/cogent3/draw/drawable.py
[CHANGED] just moved the conditional down a few lines
> BUG: allow using environment variable PLOTLY_RENDERER="sphinx_gallery"

- src/cogent3/util/table.py
- tests/test_util/test_table.py
[FIXED] when static_column_types=False, need to catch TypeError too
> BUG: catch additional case in casting to array from string

- doc/index.rst
[CHANGED] to be integrated into project docs by cogent3org repo
> DOC: tweaks to index

- pyproject.toml
- setup.py
[CHANGED] numpy no longer required for build
[CHANGED] add project urls to setup for home page, source and issue tracker
> DEV: tidy toml and add metadata

- doc/cookbook/loading_tabular.rst
- src/cogent3/parse/table.py
- tests/test_util/test_table.py
[NEW] column selection is either via column names, or index position
> ENH: FilteringParser can select specific columns

- src/cogent3/util/table.py
- tests/test_util/test_table.py
> BUG: Table.filtered and Table.count handle case where Table has no rows

- src/cogent3/core/alignment.py
NOTE: still needs to be tested
> BUG: _repr_html_ now displays correct number of seqs when truncated, related to #715

- src/cogent3/core/alignment.py
[CHANGED] Don't over-ride self, it caused bugs!
[CHANGED] CSS settings so the line height of sequence labels and sequences
is the same and both are not bold.
> MAINT: refactored Alignment.to_html() and CSS fixes

- src/cogent3/app/data_store.py
- tests/test_app/test_data_store.py
[CHANGED] that's not available in python 3.6...doh!
> API: reverted cached_property on data store

- src/cogent3/core/sequence.py
- tests/test_core/test_sequence.py
[NEW] uses COGENT3_ALIGNMENT_REPR_POLICY as per alignment
[CHANGED] moved _repr_html_ and to_html methods to SequenceI base class
so ArraySequence get's this too.
> ENH: Sequence now reads repr settings from environment var

- src/cogent3/__init__.py
- tests/test_util/test_table.py
[NEW] if you try and load a table but give it a dict, or try and make
a table and give the function a string, you're probably just using
the wrong function. Indicate that in the error message.
> ENH: more useful error messages

- src/cogent3/maths/stats/test.py
No other uses of median() found.
> #788 Discontinued cogent3.maths.stats.test.median

- src/cogent3/core/alignment.py
- src/cogent3/core/tree.py
- src/cogent3/format/alignment.py
- src/cogent3/parse/table.py
- src/cogent3/phylo/consensus.py
- src/cogent3/phylo/tree_collection.py
- src/cogent3/util/dict_array.py
- src/cogent3/util/misc.py
- src/cogent3/util/table.py
- tests/test_core/test_alignment.py
- tests/test_core/test_sequence.py
- tests/test_core/test_tree.py
- tests/test_phylo.py
- tests/test_util/test_misc.py
atomic_write now also handles expanding user home directory syntax
> Extend usage of atomic_write

- src/cogent3/util/misc.py
- tests/test_util/test_misc.py
[CHANGED] mproved variable names in key methods to make code more
readable
[NEW] now actually test a file doesn't get written if exception raised
before write is completed.
> TST: added explicit test that atomic_write works

- .github/workflows/testing_develop.yml
- setup.py
- src/cogent3/util/union_dict.py
- tox.ini
The only Python 3 version in the next stable release of Debian is 3.9
> test with Python3.9

- doc/app/app-overview.rst
- doc/examples/demo-mpi-parallel.py
- doc/examples/demo-multiprocess-parallel.py
- doc/examples/index.rst
- doc/examples/parallel.rst
- src/cogent3/app/composable.py
- src/cogent3/util/parallel.py
[NEW] added two demo scripts and an general document in examples
> DOC: added documentation for parallel computation, fixes #806

- src/cogent3/app/composable.py
- tests/test_app/test_composable.py
[NEW] both positional and key-word argument values can be provided
on construction
[NEW] docstring for user_function
> ENH: cogent3.app user_function supports default argument values

- .github/workflows/testing_develop.yml
- README.md
- setup.py
- src/cogent3/util/parallel.py
- tests/test_app/test_composable.py
- tests/test_app/test_data_store.py
- tests/test_maths/test_stats/test_contingency.py
- tests/test_util/test_misc.py
- tox.ini
Fixing issues hidden by broken CI!
> Series of patches

- src/cogent3/maths/measure.py
- tests/test_maths/test_measure.py
[FIXED] numpy.sum precision causing negative values, swapped to
using math.fsum whose algorithm is more accurate
> BUG: improve calculation of JSD

- src/cogent3/app/align.py
- src/cogent3/core/location.py
- tests/test_app/test_align.py
- tests/test_core/test_location.py
Strange bugs were difficult to debug because the code was not structured in a way that facilitated troubleshooting. This patch makes changes to simplify debugging and also fixes the recently identified bug.
> significant refactor to align_to_ref

- doc/doctest_rsts.py
- doc/examples/demo-mpi-parallel.py
- src/cogent3/evolve/models.py
- src/cogent3/evolve/solved_models.py
- tests/test_evolve/test_models.py
Nested models now reflect their appropriate name, while base models retain their base name.
> API: Nested models now reflect their appropriate name. #941

- src/cogent3/app/composable.py
- tests/test_app/test_composable.py
[CHANGED] converted appify from a class to 3-nested functions. This was done
because it allowed usage of functools.wraps to wrap the user function
and we can store a reference to that wrapped function for provision to
user_function. This was key to enabling pickling support. Failure to do this
resulted in PicklingError, function is not the same object as __main__.foo
because the latter was the decorated function.
> ENH: refactor of appify so decorated functiuons can be pickled

- src/cogent3/maths/period.py
- src/cogent3/maths/stats/period.py
- tests/test_maths/test_stats/test_period.py
[CHANGED] old names retained, with deprecation warnings
> DEP: cogent3.math periodicity classes method names pep8

- src/cogent3/app/evo.py
- tests/test_app/test_evo.py
[NEW] Improve the consistency in setting an upper bound for
rate parameters.
> ENH: add upper argument to app.evo.model

- src/cogent3/maths/measure.py
- tests/test_maths/test_measure.py
[NEW] algorithm within function made more general, no change to API
> ENH: generalise Jensen-Shannon calculations to > 2 distributions

- src/cogent3/app/data_store.py
[CHANGED] find start of the last exception traceback and display that
> ENH: more refinements on summary_logs

- src/cogent3/app/io.py
[NEW] cogent3.app.io.register_datastore_reader enables
development of third party readers / loaders to be developed.
Registering a reader class requires decorating it with the filename
suffix that will distinguish that content type. Still limited to
reading from files only.
> ENH: added a register_datastore_reader decorator

- src/cogent3/app/composable.py
[CHANGED] eliminate redundant creation of DataStoreMembers
> MAINT: tidy in apply_to

- src/cogent3/app/align.py
- src/cogent3/app/composable.py
- src/cogent3/app/dist.py
- src/cogent3/app/evo.py
- src/cogent3/app/io.py
- src/cogent3/app/sample.py
- src/cogent3/app/translate.py
- src/cogent3/app/tree.py
- tests/test_app/test_composable.py
[CHANGED] related to #1075, replaced self.func with
self.main.
This does not fully address the issue, which will require
defining an abstrcat class and method. The challenge to that is
some choices regarding the assignment to self.main are conditioned
on other parameter values.
> ENH: changed default Composable method name to main

- .github/workflows/testing_develop.yml
- src/cogent3/app/composable.py
- src/cogent3/app/io.py
- src/cogent3/app/typing.py
- src/cogent3/core/alignment.py
- tests/test_app/test_composable.py
- tests/test_app/test_dist.py
- tests/test_app/test_tree.py
DEV: remove `composable._out` attribute, remove multiple inheritance from `app.io`
> Composable refactor

- tests/test_app/test_composable.py
[CHANGED] mid-process checkpointing is no longer supported, so
testing of this feature no longer makes sense
[CHANGED] with the removal of Composable.output we are making the
binding of apps one-directional. Thus, app composition only fails
when we try and set an apps input when one has already been set.
Change test to reflect this.
> TST: update test to reflect changes in relationship between composed apps

- src/cogent3/app/composable.py
- tests/test_app/test_composable.py
- tests/test_app/test_evo.py
- tests/test_app/test_sample.py
[FIXED] was not correctly handling variable positional arguments.
Use the inspect Signature.bind_partial method to solve this correctly!
> BUG: fix bug in _new

- src/cogent3/app/composable.py
[CHANGED] The deprecation warning contains a link to a wiki page
I created which we will update when the process is nailed down.
> DEP: announce deprecation of Composable app base class

- src/cogent3/app/composable.py
- tests/test_app/test_composable.py
[CHANGED] not supporting this yet, possibly never
> MAINT: raise an exception on decorated classes that use slots

- src/cogent3/app/composable.py
[CHANGED] removed more slots related code
[CHANGED] remove methods for serialisation as no longer used
> MAINT: further tidy of define_app decorator

- doc/api/apps/composable.define_app.rst
- doc/api/index.rst
- doc/app/user_function.rst
- src/cogent3/app/composable.py
[NEW] hooked up API docs
[NEW] updated app docs to new usage of define_app for decorating
user functions.
> DOC: added docstring for define_app along with other docs

- src/cogent3/app/sample.py
- src/cogent3/core/genetic_code.py
- tests/test_core/test_genetic_code.py
- tests/test_core/test_moltype.py
[CHANGED] note name of genetic code 1 has changed from
"Standard Nuclear" to "Standard"
> ENH: updated genetic codes based latest NCBI versions

- .github/workflows/testing_develop.yml
- noxfile.py
- src/cogent3/app/composable.py
- src/cogent3/core/alphabet.py
- src/cogent3/core/moltype.py
- src/cogent3/core/sequence.py
- tests/test_core/test_alphabet.py
- tests/test_core/test_sequence.py
[CHANGED] marked four methods and two properties to be discontinued as they
overlap substantially with other methods
> MAINT: begin process of simplifying cogent3.core.alphabet

- src/cogent3/util/misc.py
- tests/test_util/test_misc.py
[CHANGED] handles built-in functions and objects
> ENH: get_object_provenance() now allows builtins

- src/cogent3/app/io_new.py
- tests/test_app/test_io_new.py
[NEW] id_from_source argument should be a callable that
generates a unique ID from input data
[NEW] docstrings for the writers
> ENH: add argument to all writer apps for a naming callback

- src/cogent3/app/data_store_new.py
- tests/test_app/test_data_store_new.py
[NEW] in data_store_new, adds an argument for deserialising which allows users
a way to deal with records stored in binary format
> ENH: new standalone summary_not_completeds function

- src/cogent3/app/align.py
- src/cogent3/app/composable.py
- src/cogent3/app/data_store_new.py
- src/cogent3/app/io_new.py
- src/cogent3/core/alignment.py
- src/cogent3/core/tree.py
- tests/test_core/test_alignment.py
[NEW] allow_gaps argument controls whether gaps included in deriving
consensus sequence.
> ENH: iupac_consensus allows ignoring gaps, fixes #1278

- doc/doctest_rsts.py
[CHANGED] run all docs converted to scripts inside a tmp directory,
avoids conflicts between processes on the same file
> DEV: make the doc testing script more robust for parallel compute

- changelog.md
> DEV: added jacard distance measure contributor

- changelog.d/20230328_072019_richard_issue1194_rename_TreeAlign.md
- doc/cookbook/building_alignments.rst
- src/cogent3/align/progressive.py
- src/cogent3/app/align.py
- src/cogent3/parse/genbank.py
- tests/test_align/test_align.py
Internal uses of TreeAlign changed to tree_align
Tests of TreeAlign maintained until deprecation
> Issue#1194: deprecated function TreeAlign for tree_align

- .github/workflows/linters.yml
- pyproject.toml
- src/cogent3/__init__.py
- src/cogent3/core/alignment.py
- tests/test_core/test_features.py
This github action will lint the entire repository on any push.
There will be a time cost associated (best guess 5-15 mins) with each push once this is merged with the main branch.
From the developers point of view when their pull request is accepted, if their code needed linting they will be out of date and need to resync their repository.
> Install precommit hook to lint Python code

- src/cogent3/core/alphabet.py
- src/cogent3/evolve/motif_prob_model.py
- tests/test_core/test_alphabet.py
[CHANGED] Separation of concerns bruh! Alphabet's should not
be responsible for probability transformation
> DEP: mark Alphabet.adapt_motif_probs as deprecated

- src/cogent3/core/moltype.py
Thanks to Kalon Peters for pointing this out!
> DOC: fixed misleading docstring om MolType

- src/cogent3/core/annotation_db.py
[FIXED] use the new start/stop properties on Location
> MAINT: fixed annotation_db genbank parsing

- src/cogent3/util/warning.py
- tests/test_util/test_warning.py
> added is_discontinued to deprecated_args decorater

- src/cogent3/core/sequence.py
- tests/test_core/test_sequence.py
> implement strict argument for Sequence.iter_kmers and .get_kmers

- src/cogent3/core/alignment.py
- src/cogent3/core/annotation_db.py
- src/cogent3/core/sequence.py
- tests/test_core/test_annotation_db.py
- tests/test_core/test_features.py
[CHANGED] both signatures now require keyword arguments
[CHANGED] all arguments are now optional, so we can create an empty
instance
> API: changed signature to GffAnnotationDb and GenbankAnnotationDb

- .github/workflows/linters.yml
> Add a check that the repo is cogent/cogent3

- README.md
README.md now includes information on funding from the Chan-Zuckerberg Initiative, with markdown text stolen from @Vini2!
> DOC: update README.md to include funding information

- src/cogent3/core/tree.py
- src/cogent3/phylo/tree_distance.py
- tests/test_core/test_tree.py
[NEW] convenience method on tree objects.
[CHANGED] replace windows line endings in phylo/tree_distance.py
> ENH: added TreeNode.lin_rajan_moret() method, fixes #1209

- doc/cookbook/annotations.rst
- doc/examples/complete_seq_features.rst
- doc/examples/seq_features.rst
[CHANGED] they are not particularly coherent, but at
least they're not failing
> DOC: get the annotation docs "passing"

- doc/api/annotation_db/annotation_db.rst
- doc/api/annotation_db/classes/cogent3.core.annotation_db.BasicAnnotationDb.rst
- doc/api/annotation_db/classes/cogent3.core.annotation_db.GenbankAnnotationDb.rst
- doc/api/annotation_db/classes/cogent3.core.annotation_db.GffAnnotationDb.rst
- doc/api/index.rst
> add annotation_db to documentation

- doc/conf.py
- pyproject.toml
[CHANGED] sphinx_panels conflicts with sphinx> 5
> DEV: using pydata theme, revert sphinx>6 change

- .github/workflows/codeql.yml
- .github/workflows/linters.yml
- .github/workflows/testing_develop.yml
[CHANGED] skip running if on master branch. This avoids having to
specify the branch being, so contributors don't have to add their
named branch to the yml.
[CHANGED] use latest version of python action
> DEV: updated testing GitHub action

- changelog.d/20230921_202221_Gavin.Huttley.md
- src/cogent3/app/evo.py
- tests/test_app/test_evo.py
[NEW] The optional tree_func argument takes a callable which
accepts an alignment and returns a corresponding cogent3 Tree.
> ENH: model app can now use a callback to get a tree

- README.md
Addresses #1599 
Logo formatting can be previewed on https://github.com/fredjaya/cogent3
> DOC: Add ANU to funding section

- src/cogent3/core/alignment.py
[CHANGED] often had a isinstance(self, ArrayAlignment) check within a
AlignmentI method which was inherited by both Alignment and
ArrayAlignment classes. I've now implemented the method on the
two classes. Makes the logic clearer and will make it easier
to remove a class when the time comes.
> MAINT: separate the Alignment and ArrayAlignment classes better

- .github/ISSUE_TEMPLATE/deprecation.md
- .github/ISSUE_TEMPLATE/discontinue.md
[CHANGED] define what I mean by those terms
> DEV: updated the issue templates for deprecated and discontinued

- src/cogent3/align/pycompare.py
- src/cogent3/core/alignment.py
- tests/test_align/test_compare.py
> bug fixes for dotplot and related code, fixes #1619

- changelog.d/20231122_134508_Gavin.Huttley.md
- src/cogent3/app/__init__.py
- tests/test_app/test_init.py
[NEW] added docstring of arg
[CHANGED] added type hint for return value
> MAINT: tweak to new available_apps() change

- changelog.d/20231201_134621_Gavin.Huttley.md
- doc/cookbook/annotation_db.rst
- doc/examples/codon_models.rst
- src/cogent3/core/alignment.py
- src/cogent3/core/annotation_db.py
- tests/test_core/test_annotation_db.py
[NEW] uses same querying interface as AnnotationDb.get_records_matching(), but
returns a new instance of self.
[NEW] added cookbook example too
[NEW] added scriv changelog entries
> ENH: AnnotationDb.subset returns a subset of rows matching condition, fixes #1641

- doc/examples/demo-mpi-parallel.py
- doc/examples/demo-multiprocess-parallel.py
- doc/examples/parallel.rst
- src/cogent3/util/parallel.py
[NEW] added parallel.get_size() function and parallel.SIZE
constant. These are the universe size (number of available CPUS)
either for multiprocess of mpi computation.
> DOC: updated to using parallel.as_completed, fixes #1611

- .gitignore
- doc/cookbook/tables.rst
- src/cogent3/util/table.py
- tests/test_util/test_table.py
Also updated `.gitignore` to ignore the wing IDE project file and `doc/_build`
> DEP: Add Table.to_pandas() #1658

- doc/draw/aln/plot_aln-dotplot-3.rst
@GavinHuttley I am not sure if there is any sphynx magic I need to do to put an image from this section in the image gallery?
> DOC: docs for using a dotplot to evaluate alignment quality, fixes #1063

- src/cogent3/align/progressive.py
- src/cogent3/app/typing.py
- src/cogent3/core/alignment.py
- src/cogent3/core/alphabet.py
- src/cogent3/core/sequence.py
[CHANGED] methods, functions, arguments marked for deletion
this year have all been deleted.
> MAINT: delete deprecated code

- src/cogent3/app/sample.py
- tests/test_app/test_sample.py
> DOC: Add docstring examples for app.sample.omit_gap_pos

- src/cogent3/core/sequence.py
- tests/test_core/test_sequence.py
Plus two additional commits to deal with the impact of having no access to my GitHub repo for 14 days.
Ignore the merge and the commit related to `Alignment.get_degapped_relative_to()`.
> ENH: added new properties on SeqView

- src/cogent3/core/sequence.py
- tests/test_core/test_sequence.py
[NEW] sliced argument controls whether truncating the represented
sequence or leaves as is.
> ENH: added SeqView.copy()

- .github/workflows/testing_develop.yml
- noxfile.py
> DEV: Coverage only runs when arguments passed through nox command, fixes #1718

- src/cogent3/app/sample.py
Suggesting changes to parameter descriptions for clarity too.
> DOC: app.sample.take_codon_positions docstring example

- src/cogent3/app/sample.py
[CHANGED] gc type bhint should be Optional[int, str]
[CHANGED] remove type info from docstring since `app_help()`
shows the signature which includes that info.
> DOC: tweaked docstring for take_codon_positions

- src/cogent3/core/annotation_db.py
Fixes an issue where somewhere, somehow, the DeprecationWarning is being filtered out. 
Addresses a comment I made in #1777
> MAINT: DeprecationWarning->UserWarning addresses comment in #1777

- changelog.d/20240328_134342_Gavin.Huttley.md
- src/cogent3/core/annotation_db.py
- tests/test_core/test_annotation_db.py
[CHANGED] make sure BytesIO instances are closed when
finished.
> MAINT: refactor sqlite array type handling

- src/cogent3/app/sample.py
Edits to @Lizhaozhe123 contributions on PR https://github.com/cogent3/cogent3/pull/1767.
Fixes #1754.
> DOC: Docstring examples for cogent3.app.sample.trim_stop_codons

- changelog.d/20240329_152534_Gavin.Huttley.md
- requirements.txt
- src/cogent3/align/pairwise.py
- src/cogent3/align/traceback.py
- src/cogent3/app/align.py
- src/cogent3/core/alignment.py
- src/cogent3/core/annotation_db.py
- src/cogent3/core/location.py
- src/cogent3/core/sequence.py
- src/cogent3/draw/dotplot.py
- src/cogent3/parse/cigar.py
- src/cogent3/parse/gbseq.py
- src/cogent3/util/parallel.py
- tests/test_app/test_align.py
- tests/test_core/test_alignment.py
- tests/test_core/test_annotation_db.py
- tests/test_core/test_features.py
- tests/test_core/test_location.py
- tests/test_core/test_maps.py
- tests/test_draw/test_dotplot.py
- tests/test_parse/test_cigar.py
IndelMap now uses numpy arrays and the API is reduced compared to the previous Map implementation.
> Refactor of map

- tests/test_core/test_location.py
[CHANGED] apparently codacy does not report all violations, so if there's
a pattern to them it's best to search throughout and address all
rather than wasting compute time on GitHub
> MAINT: yet more codacy issues

- requirements.txt
- src/cogent3/app/__init__.py
- tests/test_app/test_plugins.py
- pin stevedore
- remove deprecated list 
- clean up detritus after removing extension manager forcing
- available_apps should only return apps
- fix fragile test for help
> Address issues from the code review of plugin-support

- doc/app/app_cookbook/index-sample.rst
- doc/app/app_cookbook/sample-concat.rst
- doc/app/app_cookbook/sample-fixed-len.rst
- doc/app/app_cookbook/sample-min-len.rst
- doc/app/app_cookbook/sample-omit-bad.rst
- doc/app/app_cookbook/sample-omit-degen.rst
- doc/app/app_cookbook/sample-omit-duplicated.rst
- doc/app/app_cookbook/sample-omit-gap.rst
- doc/app/app_cookbook/sample-take-n-seqs.rst
- doc/app/app_cookbook/sample-take-pos.rst
- doc/app/app_cookbook/sample-take-seqs.rst
- doc/app/app_cookbook/sample-trim-stops.rst
- doc/app/index-cookbook.rst
- doc/cookbook/genetic_code.rst
- src/cogent3/app/sample.py
Thanks to @fredjaya great docstring examples which were inserted into the docs!!
> DOC: added sample apps to cookbook

- src/cogent3/core/sequence.py
- tests/test_core/test_alignment.py
- tests/test_core/test_sequence.py
added abstract base class `SliceRecordABC`, for recording the history of operations to be applied to some underlying data. Modified `SeqView` to inherit from `SliceRecordABC`
> NEW: abstract base class for views, fixes #1865

- src/cogent3/core/location.py
> DOC: Add IndelMap param docstring

- src/cogent3/core/new_alphabet.py
- tests/test_core/test_new_alphabet.py
[CHANGED] array_to_bytes() and bytes_to_array() now use
convert_alphabet()
> MAINT: refactor new_alphabet converter classes

- src/cogent3/core/alignment.py
- src/cogent3/core/new_alignment.py
- src/cogent3/core/new_moltype.py
- tests/test_core/test_alignment.py
- tests/test_core/test_new_alignment.py
- tests/test_core/test_new_moltype.py
A few tests marked as xfail - we should probably decide whether these are behaviours we want to support on the new sequence collection
> SequenceCollection refactor - general and annotation db methods

- src/cogent3/core/alignment.py
- src/cogent3/core/new_alignment.py
- src/cogent3/core/new_sequence.py
- src/cogent3/draw/dotplot.py
- tests/test_core/test_alignment.py
- tests/test_core/test_new_alignment.py
- add `SeqsData.to_alphabet`
- add `SequenceCollection.to_moltype`
- add `SequenceCollection.dotplot`
> Seq collections refactor

- tests/test_core/test_new_sequence.py
> TST: unmark passing xfails

- tests/test_core/test_new_sequence.py
- tests/test_core/test_sequence.py
Main thing is xfailing the serialisation of `new_sequence` objects
> TST: Port some seqview and serialisation tests

- src/cogent3/core/new_alignment.py
- src/cogent3/core/new_sequence.py
- tests/test_core/test_new_alignment.py
This PR increases the type hinting in `new_alignment.py`
> MAINT: type hinting 

- tests/test_core/test_new_sequence.py
- tests/test_core/test_sequence.py
Three different xfails here, let me know if they should be left xfailed or addressed!
> TST: xfailing sequence tests

- pyproject.toml
- requirements.txt
- src/cogent3/maths/markov.py
- src/cogent3/util/dict_array.py
- tests/test_util/test_table.py
[CHANGED] remove restriction blocking using numpy 2.0, update toml
and requirements files.
> MAINT: now support numpy 2.0

- src/cogent3/core/new_alphabet.py
- tests/test_core/test_new_alphabet.py
[NEW] added to_rich_dict(), to_json(), from_rich_dict() methods
to AlphabetABC definition.
[NEW] implement all on CharAlphabet and KmerAlphabet and register
from_rich_dict class methods as deserialiser
> ENH: implement serialisation methods on new_alphabet classes

- src/cogent3/core/new_sequence.py
- tests/test_core/test_new_sequence.py
- tests/test_core/test_sequence.py
One new xfail with no `new_sequence.SeqView.replace`
> TST: Port SeqView tests and #1915

- src/cogent3/core/new_alignment.py
- src/cogent3/core/new_sequence.py
- tests/test_core/test_new_alignment.py
- tests/test_core/test_new_sequence.py
Includes 
- serialisation and deserialisation of `Sequence` and `SequenceCollection` classes 
- primitive serialisation of `Seq(Data)View` classes and no deserialisation
addresses #1924
> ENH: deserialisation of `SequenceCollection` and `SeqsData`, fixes #1924

- src/cogent3/core/new_alignment.py
- src/cogent3/core/new_alphabet.py
- src/cogent3/core/new_moltype.py
- src/cogent3/core/new_sequence.py
- src/cogent3/core/sequence.py
- src/cogent3/data/molecular_weight.py
- tests/test_core/test_new_alignment.py
- tests/test_core/test_new_moltype.py
- tests/test_core/test_new_sequence.py
- tests/test_core/test_sequence.py
- removed `AlignedData` and tests
- porting `Moltype` methods 
- #1939
- porting `Sequence` methods
- #1941
- porting `Sequence` tests
> ENH: sequence refactor

- src/cogent3/app/align.py
- src/cogent3/app/dist.py
- src/cogent3/app/io.py
- app.io apps: added links to cookbook
- app.io some apps: removed extend docstring decorator
- app.io.load_json: add empty init for docstring
> DOC: Add app docstring examples #1636

- src/cogent3/core/alignment.py
- src/cogent3/core/new_alignment.py
- src/cogent3/core/new_alphabet.py
- src/cogent3/core/new_moltype.py
- src/cogent3/core/new_sequence.py
- tests/test_core/test_alignment.py
- tests/test_core/test_new_alignment.py
- tests/test_core/test_new_sequence.py
In this PR: 
- re-add `AlignedData` class and helper code- thanks @fredjaya!
- add `Aligned` class which wraps an `AlignedDataView`
- add `Alignment` and tests of its basic usage
> ENH: begin Alignment refactor

- changelog.d/20240731_102115_Gavin.Huttley.md
- src/cogent3/app/translate.py
- src/cogent3/core/new_alphabet.py
- tests/test_app/test_composable.py
- tests/test_app/test_translate.py
[NEW] users can now specify that all sequences in a collection are in
the nominated frame.
> ENH: select_translatable frame argument

- changelog.md
- src/cogent3/_version.py
[CHANGED] to sync with the revised workflow
> REL: bump release minor _version

- src/cogent3/align/pycompare.py
[CHANGED] move type conversion out of the loop!
> ENH: improve performance of pycompare.find_matched_paths

- src/cogent3/core/alignment.py
- src/cogent3/core/location.py
- src/cogent3/core/new_alignment.py
- src/cogent3/core/new_sequence.py
- tests/test_core/test_location.py
- tests/test_core/test_new_alignment.py
in this PR: 
- support for slicing IndelMaps with stride < 0,  fixes #1967 
- support for slicing Alignments with stride < 0 
- support for negative indexing of Alignments
> ENH: add support for reversing and strides when indexing IndelMaps and Alignments, fixes #1967

- .github/workflows/release.yml
[CHANGED] pinned to 3.13.3. Also now just test the lowest
and highest supported python versions.
> DEV: revise release action to address python 3.13.4 bug
